server:
  port: 8092 
  
#定义springmvc视图解析器    
spring:     
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
      
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.88.135:2181?backup=192.168.88.135:2182,192.168.88.135:2183


  